use proc_macro2::TokenStream;
use quote::quote;
use syn::{
    Attribute, Error, Ident, Result, Token, Visibility, braced,
    parse::{ParseStream, Parser},
};

use crate::{
    schema::{Schema, escape_cell},
    value::Value,
};

pub fn expand(schema_source: &str, macro_name: &str, input: TokenStream) -> Result<TokenStream> {
    let schema: Schema = syn::parse_str(schema_source)?;
    let instance = (|stream: ParseStream| Instance::parse(stream, &schema)).parse2(input)?;
    let resolved = instance.resolve(&schema)?;
    let doc = instance_doc(macro_name, &resolved)?;
    let generator = &schema.generator;
    let Instance {
        attrs, vis, name, ..
    } = &instance;
    // `$vis:vis` cannot match an empty visibility at the end of `[...]`.
    let vis = match vis {
        Visibility::Inherited => quote!(pub(self)),
        vis => quote!(#vis),
    };
    let field_names = resolved.iter().map(|field| field.name);
    let field_values = resolved.iter().map(|field| field.value);
    Ok(quote! {
        #generator! {
            attrs: [#(#attrs)*],
            vis: [#vis],
            name: #name,
            doc: #doc,
            #(#field_names: #field_values,)*
        }
    })
}

/// `{ATTR} VIS NAME { FIELD, ... }` with each value parsed by its schema kind.
struct Instance {
    attrs: Vec<Attribute>,
    vis: Visibility,
    name: Ident,
    fields: Vec<(Ident, Value)>,
}

impl Instance {
    fn parse(input: ParseStream, schema: &Schema) -> Result<Self> {
        let attrs = input.call(Attribute::parse_outer)?;
        let vis = input.parse()?;
        let name = input.parse()?;
        let content;
        braced!(content in input);
        let mut fields = Vec::new();
        while !content.is_empty() {
            let field_name: Ident = content.parse()?;
            let spec = schema.field(&field_name).ok_or_else(|| {
                Error::new(
                    field_name.span(),
                    format!(
                        "unknown field `{field_name}`; expected one of {}",
                        schema.expected_list()
                    ),
                )
            })?;
            content.parse::<Token![:]>()?;
            let value = spec.kind.parse_value(&content, &field_name)?;
            fields.push((field_name, value));
            if content.is_empty() {
                break;
            }
            content.parse::<Token![,]>()?;
        }
        if !input.is_empty() {
            return Err(input.error("unexpected tokens after the declaration body"));
        }
        Ok(Self {
            attrs,
            vis,
            name,
            fields,
        })
    }

    /// Every schema field in schema order, with defaults filled in.
    fn resolve<'a>(&'a self, schema: &'a Schema) -> Result<Vec<ResolvedField<'a>>> {
        let mut errors: Option<Error> = None;
        let mut push = |error: Error| match &mut errors {
            Some(errors) => errors.combine(error),
            None => errors = Some(error),
        };
        for (index, (name, _)) in self.fields.iter().enumerate() {
            if self.fields[..index].iter().any(|(earlier, _)| earlier == name) {
                push(Error::new(name.span(), format!("duplicate field `{name}`")));
            }
        }
        let mut resolved = Vec::new();
        for spec in &schema.fields {
            let given = self.fields.iter().find(|(name, _)| *name == spec.name);
            match (given, &spec.default) {
                (Some((_, value)), _) => resolved.push(ResolvedField {
                    name: &spec.name,
                    value,
                    is_default: false,
                }),
                (None, Some(default)) => resolved.push(ResolvedField {
                    name: &spec.name,
                    value: default,
                    is_default: true,
                }),
                (None, None) => push(Error::new(
                    self.name.span(),
                    format!("missing required field `{}`", spec.name),
                )),
            }
        }
        errors.map_or(Ok(resolved), Err)
    }
}

struct ResolvedField<'a> {
    name: &'a Ident,
    value: &'a Value,
    is_default: bool,
}

/// Rustdoc for the generated item: the configuration this invocation used.
fn instance_doc(macro_name: &str, fields: &[ResolvedField]) -> Result<String> {
    let mut doc = format!("Generated by `{macro_name}!`.\n\n");
    doc.push_str("| Field | Value |\n| ----- | ----- |\n");
    for field in fields {
        let marker = if field.is_default { " (default)" } else { "" };
        doc.push_str(&format!(
            "| `{}` | `{}`{marker} |\n",
            field.name,
            escape_cell(&field.value.pretty()?)
        ));
    }
    Ok(doc)
}
