use pretty_assertions::assert_eq;
use proc_macro2::TokenStream;
use quote::quote;

use crate::{
    Result, define,
    instance::expand_parts,
    schema::{Schema, macro_doc},
    template,
};

#[test]
fn template_matcher_covers_kinds_metadata_and_repetition_depths() -> Result<()> {
    let schema: Schema = syn::parse2(quote! {
        __generate {
            name: ident,
            value?: expr,
            output: ty,
            bounds: { min: expr, max: expr },
            members 1.. {
                name: ident,
                index: expr = 0,
                limits?: { min: expr, upper?: expr },
            },
        }
    })?;
    let expected = quote! {
        attrs: [$(#[$attrs:meta])*],
        vis: [$vis:vis],
        name: $name:ident,
        doc: $doc:literal,
        name: $field_name:ident,
        value: [$($field_value:expr)?],
        output: $field_output:ty,
        bounds: { min: $field_bounds_min:expr, max: $field_bounds_max:expr, },
        member_count: $member_count:literal,
        members: [$({
            index: $member_index:literal,
            attrs: [$(#[$member_attrs:meta])*],
            vis: [$member_vis:vis],
            name: $member_name:ident,
            doc: $member_doc:literal,
            name: $member_field_name:ident,
            index: $member_field_index:expr,
            limits: [$({ min: $member_field_limits_min:expr,
                upper: [$($member_field_limits_upper:expr)?], })?],
        },)*],
    };
    assert_eq!(
        template::matcher(&schema.body)?.to_string(),
        expected.to_string()
    );
    Ok(())
}

const LED_SCHEMA: &str = "__led_generate {
    /// GPIO pin.
    pin: ident,
    /// Number of LEDs.
    len: expr,
    /// PIO resource.
    pio: ident = PIO0,
    /// Color curve.
    gamma: expr = Gamma::Srgb,
}";

/// Expands `input` against a `GENERATOR { BODY }` schema, as the generated wrapper would.
fn run(schema: &str, macro_name: &str, input: TokenStream) -> Result<TokenStream> {
    let Schema { generator, body } = syn::parse_str(schema)?;
    expand_parts(macro_name, &quote!(#generator), &body, input)
}

fn pretty(tokens: TokenStream) -> Result<String> {
    Ok(prettyplease::unparse(&syn::parse2(tokens)?))
}

fn error_message(result: Result<TokenStream>) -> Option<String> {
    result.err().map(|error| {
        error
            .into_iter()
            .map(|error| error.to_string())
            .collect::<Vec<_>>()
            .join("\n")
    })
}

#[test]
fn expand_fills_defaults_in_schema_order() -> Result<()> {
    let input = quote! {
        #[derive(Debug)]
        pub(crate) Status { len: 1 + 2, pin: PIN_3 }
    };
    let doc = "Generated by `led!`.\n\n\
        | Field | Value |\n| ----- | ----- |\n\
        | `pin` | `PIN_3` |\n\
        | `len` | `1 + 2` |\n\
        | `pio` | `PIO0` (default) |\n\
        | `gamma` | `Gamma::Srgb` (default) |\n";
    let expected = quote! {
        __led_generate! {
            attrs: [#[derive(Debug)]],
            vis: [pub(crate)],
            name: Status,
            doc: #doc,
            pin: PIN_3,
            len: 1 + 2,
            pio: PIO0,
            gamma: Gamma::Srgb,
        }
    };
    assert_eq!(pretty(expected)?, pretty(run(LED_SCHEMA, "led", input)?)?);
    Ok(())
}

#[test]
fn expand_reports_unknown_field() {
    let input = quote! { Status { pin: PIN_3, length: 8 } };
    assert_eq!(
        error_message(run(LED_SCHEMA, "led", input)).as_deref(),
        Some("unknown field `length`; expected one of `pin`, `len`, `pio`, `gamma`")
    );
}

#[test]
fn expand_reports_duplicate_and_missing_together() {
    let input = quote! { Status { pin: PIN_3, pin: PIN_4 } };
    assert_eq!(
        error_message(run(LED_SCHEMA, "led", input)).as_deref(),
        Some("duplicate field `pin`\nmissing required field `len`")
    );
}

#[test]
fn expand_parses_value_by_kind() {
    let input = quote! { Status { pin: 3, len: 8 } };
    assert_eq!(
        error_message(run(LED_SCHEMA, "led", input)).as_deref(),
        Some("field `pin` expects an identifier")
    );
}

#[test]
fn define_emits_wrapper_and_bare_name_alias() -> Result<()> {
    let input = quote! {
        /// An LED strip.
        #[cfg(not(feature = "host"))]
        pub led => __led_generate { pin: ident }
    };
    let doc = "\n\n**Syntax:**\n\n```text\n\
        led! {\n    [<attributes>] [<visibility>] <Name> {\n\
        \x20       pin: <ident>,\n\
        \x20   }\n}\n```\n\n**Fields:**\n\n\
        | Field | Kind | Default | Description |\n\
        | ----- | ---- | ------- | ----------- |\n\
        | `pin` | ident | required |  |\n";
    let expected = quote! {
        #[cfg(not(feature = "host"))]
        #[doc = #doc]
        #[doc(hidden)]
        #[macro_export]
        macro_rules! __const_structures_wrapper_led {
            ($($input:tt)*) => {
                $crate::__const_structures_expand! {
                    macro_name: "led",
                    generator: { $crate::__led_generate },
                    schema: { pin: ident },
                    input: { $($input)* },
                }
            };
        }

        /// An LED strip.
        #[cfg(not(feature = "host"))]
        #[doc(inline)]
        pub use __const_structures_wrapper_led as led;
    };
    assert_eq!(expected.to_string(), define(input)?.to_string());
    Ok(())
}

#[test]
fn define_rejects_absolute_generator_path() {
    let input = quote! { pub led => ::demo::__led_generate { pin: ident } };
    assert_eq!(
        error_message(define(input)).as_deref(),
        Some("the generator path is relative to this crate's root; drop the leading `::`")
    );
}

#[test]
fn expand_parses_wrapper_input() -> Result<()> {
    let input = quote! {
        macro_name: "led",
        generator: { crate::__led_generate },
        schema: { pin: ident },
        input: { Status { pin: PIN_3 } },
    };
    let doc = "Generated by `led!`.\n\n| Field | Value |\n| ----- | ----- |\n| `pin` | `PIN_3` |\n";
    let expected = quote! {
        crate::__led_generate! {
            attrs: [],
            vis: [pub(self)],
            name: Status,
            doc: #doc,
            pin: PIN_3,
        }
    };
    assert_eq!(pretty(expected)?, pretty(crate::expand(input)?)?);
    Ok(())
}

const STRIPS_SCHEMA: &str = "__strips_generate {
    /// Shared bus.
    bus: ident = BUS0,
    /// One strip per member.
    members 1..=2 {
        /// Data pin.
        pin: ident,
        /// Channel.
        dma: ident = by_index[DMA0, DMA1],
        /// Optional panel geometry.
        panel?: {
            /// Width in pixels.
            width: expr,
            /// Font.
            font: expr = Font::Small,
        },
    },
}";

#[test]
fn expand_members_with_index_defaults_and_optional_block() -> Result<()> {
    let input = quote! {
        pub Strips {
            First { pin: P0 },
            Second { panel: { width: 12 }, pin: P1 },
        }
    };
    let group_doc = "Generated by `strips!`.\n\n\
        | Field | Value |\n| ----- | ----- |\n\
        | `bus` | `BUS0` (default) |\n\
        \nMembers: `First`, `Second`.\n";
    let first_doc = "Member `First` of `Strips`, generated by `strips!`.\n\n\
        | Field | Value |\n| ----- | ----- |\n\
        | `pin` | `P0` |\n\
        | `dma` | `DMA0` (default) |\n\
        | `panel` | `(not set)` |\n";
    let second_doc = "Member `Second` of `Strips`, generated by `strips!`.\n\n\
        | Field | Value |\n| ----- | ----- |\n\
        | `pin` | `P1` |\n\
        | `dma` | `DMA1` (default) |\n\
        | `panel` | `{ width: 12, font: Font::Small }` |\n";
    let expected = quote! {
        __strips_generate! {
            attrs: [],
            vis: [pub],
            name: Strips,
            doc: #group_doc,
            bus: BUS0,
            member_count: 2,
            members: [
                {
                    index: 0,
                    attrs: [],
                    vis: [pub],
                    name: First,
                    doc: #first_doc,
                    pin: P0,
                    dma: DMA0,
                    panel: [],
                },
                {
                    index: 1,
                    attrs: [],
                    vis: [pub],
                    name: Second,
                    doc: #second_doc,
                    pin: P1,
                    dma: DMA1,
                    panel: [{ width: 12, font: Font::Small, }],
                },
            ],
        }
    };
    assert_eq!(
        pretty(expected)?,
        pretty(run(STRIPS_SCHEMA, "strips", input)?)?
    );
    Ok(())
}

#[test]
fn expand_reports_member_errors_together() {
    let input = quote! {
        Strips {
            A { pin: P0, panel: { font: F } },
            A { pin: P1 },
            C { pin: P2 },
        }
    };
    assert_eq!(
        error_message(run(STRIPS_SCHEMA, "strips", input)).as_deref(),
        Some(
            "`strips!` takes 1 to 2 members; found 3\n\
             duplicate member `A`\n\
             missing required field `width`\n\
             field `dma` has no default for member index 2; give it explicitly"
        )
    );
}

#[test]
fn expand_rejects_members_where_schema_has_none() {
    let input = quote! { Status { pin: PIN_3, len: 1, Extra { pin: PIN_4 } } };
    assert_eq!(
        error_message(run(LED_SCHEMA, "led", input)).as_deref(),
        Some("`Status` takes fields only; expected one of `pin`, `len`, `pio`, `gamma`")
    );
}

#[test]
fn schema_rejects_by_index_outside_members() {
    let input = quote! { pub bad => gen { dma: ident = by_index[A, B] } };
    assert_eq!(
        error_message(define(input)).as_deref(),
        Some("`by_index` defaults are allowed only in member fields")
    );
}

#[test]
fn schema_rejects_optional_with_default() {
    let input = quote! { pub bad => gen { pin?: ident = A } };
    assert_eq!(
        error_message(define(input)).as_deref(),
        Some("an optional (`?`) field cannot also have a default")
    );
}

#[test]
fn define_documents_members_and_blocks() -> Result<()> {
    let schema: Schema = syn::parse_str(STRIPS_SCHEMA)?;
    let doc = macro_doc(&syn::parse_quote!(strips), &schema)?;
    let expected = "\n\n**Syntax:**\n\n```text\n\
        strips! {\n    [<attributes>] [<visibility>] <Name> {\n\
        \x20       bus: <ident>, // optional, default: BUS0\n\
        \x20       [<attributes>] <MemberName> { // 1 to 2 members; visibility comes from the group\n\
        \x20           pin: <ident>,\n\
        \x20           dma: <ident>, // optional, default: by member index: DMA0, DMA1\n\
        \x20           panel: { // optional\n\
        \x20               width: <expr>,\n\
        \x20               font: <expr>, // optional, default: Font::Small\n\
        \x20           },\n\
        \x20       },\n\
        \x20   }\n}\n```\n\n**Fields:**\n\n\
        | Field | Kind | Default | Description |\n\
        | ----- | ---- | ------- | ----------- |\n\
        | `bus` | ident | `BUS0` | Shared bus. |\n\
        \n**Member fields** (1 to 2 members; One strip per member.):\n\n\
        | Field | Kind | Default | Description |\n\
        | ----- | ---- | ------- | ----------- |\n\
        | `pin` | ident | required | Data pin. |\n\
        | `dma` | ident | by member index: `DMA0`, `DMA1` | Channel. |\n\
        | `panel` | block | optional | Optional panel geometry. |\n\
        | `panel.width` | expr | required | Width in pixels. |\n\
        | `panel.font` | expr | `Font::Small` | Font. |\n";
    assert_eq!(expected, doc);
    Ok(())
}

#[test]
fn default_display_overrides_docs_but_not_generated_tokens() -> Result<()> {
    let schema_source = "__gen {
        /// Color curve.
        #[default_display = \"Gamma::Srgb\"]
        gamma: expr = ::demo::led_strip::Gamma::Srgb,
    }";
    let schema: Schema = syn::parse_str(schema_source)?;
    let doc = macro_doc(&syn::parse_quote!(led), &schema)?;
    assert!(doc.contains("gamma: <expr>, // optional, default: Gamma::Srgb\n"));
    assert!(doc.contains("| `gamma` | expr | `Gamma::Srgb` | Color curve. |\n"));
    let instance_doc = "Generated by `led!`.\n\n\
        | Field | Value |\n| ----- | ----- |\n\
        | `gamma` | `Gamma::Srgb` (default) |\n";
    let expected = quote! {
        __gen! {
            attrs: [],
            vis: [pub(self)],
            name: Strip,
            doc: #instance_doc,
            gamma: ::demo::led_strip::Gamma::Srgb,
        }
    };
    assert_eq!(
        pretty(expected)?,
        pretty(run(schema_source, "led", quote! { Strip {} })?)?
    );
    Ok(())
}

#[test]
fn schema_rejects_default_display_without_default() {
    let input = quote! { pub bad => gen { #[default_display = "X"] pin: ident } };
    assert_eq!(
        error_message(define(input)).as_deref(),
        Some("`default_display` needs a single default value (`= ...`)")
    );
}

#[test]
fn expand_explains_colon_after_declaration_name() {
    let input = quote! { Strips { First: { pin: P0 } } };
    assert_eq!(
        error_message(run(STRIPS_SCHEMA, "strips", input)).as_deref(),
        Some("remove the `:` after `First`; declarations are written `First { ... }`")
    );
}

#[test]
fn expand_rejects_member_visibility() {
    let input = quote! { pub Strips { pub(crate) First { pin: P0 } } };
    assert_eq!(
        error_message(run(STRIPS_SCHEMA, "strips", input)).as_deref(),
        Some("members take their group's visibility; remove this visibility")
    );
}

#[test]
fn members_may_have_no_upper_limit() -> Result<()> {
    let schema = "__lcds_generate { members 1.. { address: expr } }";
    let input = quote! { Lcds { A { address: 1 }, B { address: 2 }, C { address: 3 } } };
    let output = run(schema, "lcds", input)?.to_string();
    assert!(output.contains("member_count : 3"), "{output}");
    assert_eq!(
        error_message(run(schema, "lcds", quote! { Lcds {} })).as_deref(),
        Some("`lcds!` takes at least 1 members; found 0")
    );
    Ok(())
}
