use pretty_assertions::assert_eq;
use proc_macro2::TokenStream;
use quote::quote;

use crate::{Result, define, expand};

const LED_SCHEMA: &str = "::demo::__led_generate {
    /// GPIO pin.
    pin: ident,
    /// Number of LEDs.
    len: expr,
    /// PIO resource.
    pio: ident = PIO0,
    /// Color curve.
    gamma: expr = Gamma::Srgb,
}";

fn pretty(tokens: TokenStream) -> Result<String> {
    Ok(prettyplease::unparse(&syn::parse2(tokens)?))
}

fn error_message(result: Result<TokenStream>) -> Option<String> {
    result.err().map(|error| {
        error
            .into_iter()
            .map(|error| error.to_string())
            .collect::<Vec<_>>()
            .join("\n")
    })
}

#[test]
fn expand_fills_defaults_in_schema_order() -> Result<()> {
    let input = quote! {
        #[derive(Debug)]
        pub(crate) Status { len: 1 + 2, pin: PIN_3 }
    };
    let doc = "Generated by `led!`.\n\n\
        | Field | Value |\n| ----- | ----- |\n\
        | `pin` | `PIN_3` |\n\
        | `len` | `1 + 2` |\n\
        | `pio` | `PIO0` (default) |\n\
        | `gamma` | `Gamma::Srgb` (default) |\n";
    let expected = quote! {
        ::demo::__led_generate! {
            attrs: [#[derive(Debug)]],
            vis: [pub(crate)],
            name: Status,
            doc: #doc,
            pin: PIN_3,
            len: 1 + 2,
            pio: PIO0,
            gamma: Gamma::Srgb,
        }
    };
    assert_eq!(pretty(expected)?, pretty(expand(LED_SCHEMA, "led", input)?)?);
    Ok(())
}

#[test]
fn expand_reports_unknown_field() {
    let input = quote! { Status { pin: PIN_3, length: 8 } };
    assert_eq!(
        error_message(expand(LED_SCHEMA, "led", input)).as_deref(),
        Some("unknown field `length`; expected one of `pin`, `len`, `pio`, `gamma`")
    );
}

#[test]
fn expand_reports_duplicate_and_missing_together() {
    let input = quote! { Status { pin: PIN_3, pin: PIN_4 } };
    assert_eq!(
        error_message(expand(LED_SCHEMA, "led", input)).as_deref(),
        Some("duplicate field `pin`\nmissing required field `len`")
    );
}

#[test]
fn expand_parses_value_by_kind() {
    let input = quote! { Status { pin: 3, len: 8 } };
    assert_eq!(
        error_message(expand(LED_SCHEMA, "led", input)).as_deref(),
        Some("field `pin` expects an identifier")
    );
}

#[test]
fn define_documents_fields() -> Result<()> {
    let schema: TokenStream = LED_SCHEMA.parse()?;
    let input = quote! {
        /// An LED strip.
        pub led => #schema
    };
    let schema_source = schema.to_string();
    let doc = "\n\n**Syntax:**\n\n```text\n\
        led! {\n    [<attributes>] [<visibility>] <Name> {\n\
        \x20       pin: <ident>,\n\
        \x20       len: <expr>,\n\
        \x20       pio: <ident>, // optional, default: PIO0\n\
        \x20       gamma: <expr>, // optional, default: Gamma::Srgb\n\
        \x20   }\n}\n```\n\n**Fields:**\n\n\
        | Field | Kind | Default | Description |\n\
        | ----- | ---- | ------- | ----------- |\n\
        | `pin` | ident | required | GPIO pin. |\n\
        | `len` | expr | required | Number of LEDs. |\n\
        | `pio` | ident | `PIO0` | PIO resource. |\n\
        | `gamma` | expr | `Gamma::Srgb` | Color curve. |\n";
    let expected = quote! {
        /// An LED strip.
        #[doc = #doc]
        #[proc_macro]
        pub fn led(input: ::proc_macro::TokenStream) -> ::proc_macro::TokenStream {
            ::const_structures::__core::expand(#schema_source, "led", input.into())
                .unwrap_or_else(|error| error.into_compile_error())
                .into()
        }
    };
    assert_eq!(pretty(expected)?, pretty(define(input)?)?);
    Ok(())
}

#[test]
fn define_as_names_the_macro_separately_from_the_function() -> Result<()> {
    let schema = quote! { ::demo::__led_generate { pin: ident } };
    let input = quote! { pub rp_led as led => #schema };
    let schema_source = schema.to_string();
    let doc = "\n\n**Syntax:**\n\n```text\n\
        led! {\n    [<attributes>] [<visibility>] <Name> {\n\
        \x20       pin: <ident>,\n\
        \x20   }\n}\n```\n\n**Fields:**\n\n\
        | Field | Kind | Default | Description |\n\
        | ----- | ---- | ------- | ----------- |\n\
        | `pin` | ident | required |  |\n";
    let expected = quote! {
        #[doc = #doc]
        #[proc_macro]
        pub fn rp_led(input: ::proc_macro::TokenStream) -> ::proc_macro::TokenStream {
            ::const_structures::__core::expand(#schema_source, "led", input.into())
                .unwrap_or_else(|error| error.into_compile_error())
                .into()
        }
    };
    assert_eq!(pretty(expected)?, pretty(define(input)?)?);
    Ok(())
}
